name: Create Release
on:
    push:
        tags:
          - '*'
jobs:
  Create-Release:
    runs-on: ubuntu-latest
    permissions:
        contents: write
    steps:
    - uses: actions/checkout@master

    - name: Build Release
      run: |
        make INSTALL-DEPS
        make build

    - name: Archive Release
      uses: thedoctor0/zip-release@0.7.5
      with:
        type: 'zip'
        path: '/tmp/release'
        filename: 'release.zip'
        exclusions: '*.git* /*node_modules/* .editorconfig'

    - name: Upload Release
      uses: ncipollo/release-action@v1.12.0
      with:
        artifacts: "release.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
